### ISSUE TITLE
HTTPError : 404

### ISSUE THREAD

**Issue by computer007** [notro/rpi-source#14]
Hello,
With new kernel (4.1.x) I can't manage to download the latest kernel sources.

When I run ```REPO_URI=https://github.com/notro/rpi-firmware rpi-source --nomake --skip-gcc```, I get:
```
*** rpi-update: https://github.com/notro/rpi-firmware

 *** Firmware revision: b2f5782d2a61cdfa1967942d34eae48900266ae1

 *** Linux source commit: 5d5a5ceb829329f490dd1c5cb634da66ef5d0f92

 *** Kernel source already installed: /home/pi/linux-5d5a5ceb829329f490dd1c5cb634da66ef5d0f92
```

I dont' understand where the "Linux source commit" version comes from, but this was the previous one I got installed.

When I basically run ```rpi-source```, here is the output:
```
 *** gcc version check: OK

 *** rpi-update: https://github.com/Hexxeh/rpi-firmware

 *** Firmware revision: b2f5782d2a61cdfa1967942d34eae48900266ae1
ERROR:
Couldn't download https://raw.githubusercontent.com/Hexxeh/rpi-firmware/b2f5782d2a61cdfa1967942d34eae48900266ae1/git_hash, HTTPError: 404

Help: https://github.com/notro/rpi-source/wiki
```

Following the link effectively leads to a "Not found" page.

Am I missing something? (note that I have run ```sudo modprobe configs```)

Thank you.

**Comment by notro** [comment]
You have 2 different runs here, with and without REPO_URI set.
If you have the fbtft firmware, you need to set REPO_URI.

rpi-source looks in /boot/.firmware_revision to find the firmware commit.
Then it looks up the github repo and finds the kernel source commit located in the git_hash file.
REPO_URI must be set for the fbtft firmware or else it looks in the Hexxeh repo where there's no such commit.

Ref: https://github.com/notro/rpi-source/blob/master/rpi-source#L209
