### ISSUE TITLE
Pi3 support

### ISSUE THREAD

**Issue by deckers** [notro/rpi-source#22]
Will there be support for Pi3 kernels, too?

Linux pi3 4.4.6+ #1 SMP PREEMPT Wed Apr 13 19:30:58 CEST 2016 armv7l GNU/Linux :
```
rpi-source --skip-gcc
ERROR:
Can't find a source for this kernel
```

Regards
Joachim

**Comment by notro** [comment]
That doesn't look like an official kernel, the latest one is build 880:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.8-v7+ #880 SMP Fri Apr 22 21:55:04 BST 2016 armv7l GNU/Linux
```

**Comment by deckers** [comment]
Sorry - my fault. I should ask my question in a xbian forum ;-)
