### ISSUE TITLE
[Info] Delete data in homedir

### ISSUE THREAD

**Issue by Ivan-Roger** [notro/rpi-source#27]
When using this tool it seems that data is stored in the homedir.
Is there any way to delete it or to move it somewhere else ?

Thanks in advance.

**Comment by notro** [comment]
If you try ```rpi-source -h```, you will see that there's a --dest argument.

**Comment by Ivan-Roger** [comment]
Oh, nice. I didn't check.
Where do you reckon I should place the data ?
Is /usr/ OK ?

**Comment by notro** [comment]
I don't know.

**Comment by Ivan-Roger** [comment]
Ok, anyway thanks
