### ISSUE TITLE
Privilage Level

### ISSUE THREAD

**Issue by LPFraile** [notro/rpi-source#28]
Hello 
I would like to ask if the lodable kernel modules that can be added it on the described way run with privilage levels. I asked because when i try on my module to write on an specific coprocessor ARMv7 register that need privilages make the system stack.

**Comment by notro** [comment]
A kernel module built using rpi-source acts the same as the other modules, except for the [kernel taint](http://unix.stackexchange.com/questions/118116/linux-what-is-a-tainted-kernel) due to being an out-of-tree module.
I have no knowledge about the arm processor
