### ISSUE TITLE
OSMC: ERROR: Can't find source for this kernel 

### ISSUE THREAD

**Issue by vjr2** [notro/rpi-source#30]
`osmc@osmc:~$ rpi-source

 *** gcc version check: OK
ERROR:
Can't find a source for this kernel

Help: https://github.com/notro/rpi-source/wiki
osmc@osmc:~$
`

I just installed the gcc and did the `sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source && sudo chmod +x /usr/bin/rpi-source && /usr/bin/rpi-source -q --tag-update` install thing.

It doesn't matter if I skip gcc nor I run --verbose it's always the same error. I'm using OSMC in my raspberry pi. How can I fix this?

**Comment by notro** [comment]
rpi-source is for kernels installed with rpi-update.
