### ISSUE TITLE
When will Python 3 support be provided?

### ISSUE THREAD

**Issue by IvanFarkas** [notro/rpi-source#34]
When will **Python 3** support be provided, please?

**Error:**
```
File "/usr/bin/rpi-source", line 105
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax
```

**Comment by notro** [comment]
When someone sends fixes it and sends a Pull Request :-)
I haven't got time to do it myself.
I'm suprised that rpi-source is still in demand. Doesn't even Rasbpian provide a kernel headers package now?
