### ISSUE TITLE
Version mismatch when running rpi-update and package manager

### ISSUE THREAD

**Issue by daladim** [notro/rpi-source#39]
Hello,

I have been successfully using rpi-source for a few times now.
However, I have just let apt-get upgrade the package raspberrypi-kernel.
This seems to confuse rpi-source, which keeps grabbing the older sources.

My previous kernel was 4.9.80-v7+, apt-get upgraded it to 4.14.30-v7+.
When I run rpi-source (even after a reboot), it keeps detecting an older firmware/linux source commit:
 *** Firmware revision: 5c80565c5c0c7f820258c792a98b56f22db2dd03
 *** Linux source commit: a2f34d45809d8685bca1e91989e35746499ac400

I think I already had such an issue, and running rpi-update with a newer kernel "fixed" the issue.
But do you think it would be useful to have rpi-source check how the kernel was actually installed, and fetch the correct sources ?

Thanks

**Comment by notro** [comment]
Try deleting ```/boot/.firmware_revision```. 
Ref: https://github.com/notro/rpi-source/blob/master/rpi-source#L316-L322

There's a kernel header package now, so rpi-source is just for special cases: https://github.com/notro/rpi-source/wiki
