### ISSUE TITLE
.config /proc/config.gz is available at /boot/config-3.12-1-rpi

### ISSUE THREAD

**Issue by timrterrible** [notro/rpi-source#5]
Is there any way to redirect rpi-source to pick the version up in /boot ?

**Comment by notro** [comment]
rpi-build has been discontinued: https://github.com/notro/rpi-source/wiki

**Comment by notro** [comment]
rpi-source isn't discontinued after all, reopen if it's still an issue.

**Comment by divergentdave** [comment]
Running `sudo modprobe configs` first worked for me, as that made `/proc/config.gz` show up in the file system.
